Sprint2/step1
peterkarpov/react-burger pull request #3
Opened 2021-08-03 16:36 UTC by peterkarpov

Добрый день) У меня так вышло, что у BurgerConstructor нет как такового собственного состояния, у корневого App есть один большой state, который пробрасывает props, а изменяется проброшенными методами. Но я вынес отдельно selectedIngredientsId в BurgerConstructorContext, не знаю на сколько это правильно)

2021-08-04 15:53 UTC, AygulMalikova requested changes
Хорошая работа! У вас структурированный и чистый код, разделенный на компоненты.

Но есть небольшие замечания. В первую очередь прошу вас обратить внимание функциональность проекта (добавление/удаление ингредиентов). Также прошу обратить внимание на следующие моменты:

- использование const вместо let
- дублирование типа ингредиента
- единообразие кода в написании компонентов и файлов со стилями
- использование одного из подходов типизации

Желаю вам удачи!

2021-08-04 15:53 UTC, AygulMalikova commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +                    let items = getItemsByType(type, state.currentItems);
Если переменная объявлена ​​с помощью `let`, ее значение следует переписать напрямую в коде. Если значение переменной никогда не перезаписывается напрямую, оно должно быть объявлено с помощью `const`. Это помогает другим разработчикам понять назначение переменной. Имейте в виду, что добавление элемента в массив или обновление свойства объекта - это не то же самое, что перезапись самой переменной. Если изменяется только внутреннее состояние переменных, объявите их с помощью `const`.

2021-08-04 15:53 UTC, AygulMalikova commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +        _id: PropTypes.string,
Как вы можете заметить, тип ингредиента дублируется в нескольких компонентах. Представьте, что в один момент необходимо будет добавить/удалить/изменить одно поле, и тогда это придется делать в нескольких местах. Это нарушает принцип DRY (про него можно почитать в этой статье https://habr.com/ru/post/144611/). Вам следует вынести в отдельный тип, разместить его внутри utils и импортировать внутри компонентов, где он используется.

2021-08-04 15:53 UTC, AygulMalikova commented on src/components/App/App.tsx
Если нажать на ингредиент сразу после того как приложение загрузилось, то оно падает с ошибкой Cannot read property 'image_large' of undefined (https://prnt.sc/1j2892j). Однако если сначала переключить табы  и потом только нажать на ингредиент, то модальное окно открывается без ошибок. 

Также прошу вас обратить внимание, что при нажатии на ингредиент он не должен добавляться в конструктор. На следующем этапе вы реализуете добавление ингредиентов в конструктор с помощью DND, а пока что вы можете захардкодить ингредиенты в конструкторе. 

Если из конструктора удаляется ингредиент, то сумма заказа не уменьшается. Пожалуйста, исправьте, чтобы сумма менялась динамически

2021-08-04 15:53 UTC, AygulMalikova commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +function BurgerConstructor(props: { data: IDataItem[], completeCheckout: (orderData: any) => void }) {
Нет необходимости использовать и typescript, и propTypes для описания пропсов. Пожалуйста, выберите один из подходов. Если вы будете использовать typescript, то в этом случае вам следует явно указывать типы вместо any

2021-08-04 15:53 UTC, AygulMalikova commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +interface IBurgerConstructorContext {
Интерфейс контекста следует вынести в отдельный файл (например, в файл BurgerConstructorContext.jsx)

2021-08-04 15:53 UTC, AygulMalikova commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +function BurgerIngredients(props: IBurgerIngredientsProps) {
Было бы лучше, если бы вы во всем проекте использовали единый подход: либо все на классовых компонентах, либо на функциональных (этот вариант предпочтительней). Тоже самое и с файлами со стилями: сейчас у вас встречаются .module.less  и .module.css, но желательно выбрать один подход

2021-08-05 10:17 UTC, peterkarpov commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +function BurgerIngredients(props: IBurgerIngredientsProps) {
К сожалению не могу импортировать файлы LESS напрямую, так как для этого мне нужно отредактировать файл webpack.config, а мы отложили это на следующие спринты. CSS из LESS у меня сейчас генерирует среда разработки, в последствии это будет компилятор.

2021-08-05 10:19 UTC, peterkarpov commented on src/components/App/App.tsx
Спасибо, не заметил) сейчас убрал добавление по клику и поставил автогенератор на элементы в конструкторе по умолчанию.

2021-08-05 15:17 UTC, AygulMalikova commented
Ваша работа принята, я вас поздравляю! Все ошибки исправлены и все условия задания выполнены. У вас отличный код, поделенный на компоненты. Так держать! Еще раз поздравляю и желаю вам дальнейших успехов!

2021-08-09 05:07 UTC, merged